export const POKEMON_DATA = {
  BLASTOISE: {
    name: "BLASTOISE",
    level: 50,
    maxHp: 100,
    attack: 83,
    defense: 100,
    moves: [
      { name: "DEATH", power: 1000 },
      { name: "HYDRO PUMP", power: 50 },
      { name: "HYDRO CANNON", power: 45 },
      { name: "WATER GUN", power: 50 },
    ],
  },
  VENUSAUR: {
    name: "VENUSAUR",
    level: 50,
    maxHp: 100,
    attack: 82,
    defense: 83,
    moves: [
      { name: "TACKLE", power: 10 },
      { name: "RAZOR LEAF", power: 55 },
      { name: "TAKE DOWN", power: 45 },
      { name: "POWER WHIP", power: 50 },
    ],
  },
  CHARIZARD: {
    name: "CHARIZARD",
    level: 55,
    maxHp: 110,
    attack: 84,
    defense: 78,
    moves: [
      { name: "FLAMETHROWER", power: 90 },
      { name: "DRAGON CLAW", power: 80 },
      { name: "FIRE SPIN", power: 35 },
      { name: "WING ATTACK", power: 60 },
    ],
  },
  PIKACHU: {
    name: "PIKACHU",
    level: 45,
    maxHp: 80,
    attack: 55,
    defense: 40,
    moves: [
      { name: "THUNDER SHOCK", power: 40 },
      { name: "QUICK ATTACK", power: 40 },
      { name: "THUNDERBOLT", power: 90 },
      { name: "IRON TAIL", power: 100 },
    ],
  },
  GYARADOS: {
    name: "GYARADOS",
    level: 60,
    maxHp: 120,
    attack: 125,
    defense: 79,
    moves: [
      { name: "DRAGON RAGE", power: 60 },
      { name: "HYDRO PUMP", power: 110 },
      { name: "ICE FANG", power: 65 },
      { name: "HYPER BEAM", power: 150 },
    ],
  },
  SNORLAX: {
    name: "SNORLAX",
    level: 58,
    maxHp: 160,
    attack: 110,
    defense: 65,
    moves: [
      { name: "BODY SLAM", power: 85 },
      { name: "REST", power: 0 },
      { name: "HYPER BEAM", power: 150 },
      { name: "CRUNCH", power: 80 },
    ],
  },
};